name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      ##- name: Run update_csv script
        ##run: |
          ##cd scripts
          ##python update_csv.py ../data/input.csv ../data/output.csv

      - name: Run tests
        run: |
          cd scripts
          python tests.py
